Repository HerySon/teaching_ml_2023, pull requests merged in 2023-04, with the labels that each got.

#60 Tache4.0_ThomasL
  notebooks/univariate_dataviz.ipynb
  scripts/univiariate_dataviz.py
Labels: Good code

#38 Tache3.0_ThomasL
  notebooks/test.ipynb
  scripts/outliers.py
Labels: minor corrections, Good code

#83 4.6 thaize
  requirements.txt
  scripts/categorical_viz.py
  scripts/countries_viz.py
Labels: Good code

#1 Tache1.1 joelle
  scripts/features_encoding.py
Labels: additional requests, Good code

#3 Tache3.0_Joelle
  scripts/outliers.py
Labels: additional requests

#24 1.1_EncoderValeursNonNumeriques_GuillaumeCHUPE
  #1.1_EncoderValeursNonNumeriques_GuillaumeCHUPE.py
Labels: Good code

#5 Commit function to remove incoherent values.
  scripts/rm_incoherent_values.py
Labels: minor corrections

#6 Function to scale numeric features
  scripts/scaling.py
Labels: Good code

#7 4.0_Visualisation_GuillaumeCHUPE
  4.0_Visualisation_GuillaumeCHUPE/#4.0_visualisation_GC.py
  requirements.txt
Labels: Good code

#9 1.0_NettoyageValeursProblematiques_GuillaumeCHUPE
  1.0_NettoyageValeursProblematiques_GuillaumeCHUPE/1.0_NettoyageValeursProblematiques_GuillaumeCHUPE.py
Labels: additional requests, minor corrections

#18 0.0_Filtrage_GuillaumeCHUPE
  scripts/0.0_Filtrage_GuillaumeCHUPE.py
Labels: major corrections

#19 0 filtre df eghiazarian sacha
  scripts/datas_filter.py
Labels: minor corrections

#87 Grace tache 5.0
  scripts/kmeans.py
  tests/test.ipynb
Labels: minor corrections

#17 Function to fit DBSCAN
  scripts/dbscan.py
Labels: Good code

#16 PCA and plots
  scripts/linear_feature_reduction.py
Labels: Good code

#23 2.0 thaize
  scripts/scaling.py
Labels: Good code

#51 Tache4.1 Visualisation multivariée des données
  scripts/Reduction de variables avec UMAP.py
  scripts/Visualisation multivariée.py
Labels: Good code

#72 4-3_Embeding_visualization_EGHIAZARIAN_Sacha
  scripts/Embeding_visualizer.py
Labels: Good code

#31 4.3_thaize
  scripts/tsne.py
  scripts/utils.py
Labels: Good code

#75 Alimou tache4.5
  scripts/reduction.py
Labels: corrections_still_needed

#40 Gérer les valeurs aberrantes
  scripts/Valeurs_aberrantes.py
  tests/test_valeurs_abberantes.py
Labels: Good code, corrections_still_needed

#74 Tache5.1_ThomasL
  notebooks/kmeans.ipynb
  notebooks/univariate_dataviz.ipynb
  scripts/agnes.py
  scripts/dbscan.py
  scripts/gmm.py
  scripts/kmeans.py
  scripts/univiariate_dataviz.py
Labels: Good code, corrections_still_needed
